### ISSUE TITLE
Confundes str() con print()

### ISSUE THREAD

**Issue by ssaavedra** [franrua/charla_1#2]
Dis en **Funcións incorporadas** que print() *devolve* a representación en caracteres, cando iso faino a función predefinida [`str()`][str]; mentres que [`print()`][print] non devolve ningún valor (i.e., devolve `None`) e produce o *efecto colateral* de mostrar pola saída estándar o que se lle pon, na representación que `str()` produce do argumento.

  [print]: https://docs.python.org/3/library/functions.html#print
  [str]: https://docs.python.org/3/library/stdtypes.html#str

**Comment by franrua** [comment]
Correxido.
