### ISSUE TITLE
A definición dun dicionario non se ve nas diapos

### ISSUE THREAD

**Issue by ssaavedra** [franrua/charla_1#3]
Nas diapositivas non se ven os `{}` que farían falta para declarar un dicionario. Non comprobei, pero seguramente é porque precises usar `\{` en lugar de `{` en LaTeX.

**Comment by franrua** [comment]
Certamente esquencérame de poñer os carñacteres de escapado. Aproveitei para engadir a definición de unha lista e de un diccionario con contido.
