### ISSUE TITLE
En Python é bo estilo non poñer parénteses nos if

### ISSUE THREAD

**Issue by ssaavedra** [franrua/charla_1#4]
Os if en Python son máis idiomáticos se a condición a testear non se atopa entre parénteses, así:

    if test1:
      something
    else if test2:
      otherthing
    else:
      pass

**Comment by ssaavedra** [comment]
O mesmo co while

**Comment by franrua** [comment]
Arranxado, tanto nas diapositivas coma no código. Aínda así poida que me quede algún erro residual por ahí. A culpa é de C e de Java, que me teñen mal acostumbrado.

**Comment by ssaavedra** [comment]
Entendo o que dis :-)
