### ISSUE TITLE
O texto da licencia non se corresponde cos logos

### ISSUE THREAD

**Issue by ssaavedra** [franrua/charla_1#5]
Nos logos da licencia CC aparece o glifo de "NonCommercial", mentres que a licencia se le como de Recoñecemento-CompartirIgual.

As creative commons non-commercial [non son licencias de cultura libre][1] e non poderían entrar ao amparo de documentación libre nos GPUL Labs. Se o que queriades é o de que a licencia sexa CC BY-SA, pídovos que eliminedes o símbolo do dólar coa aspa para deixalo máis claro.

  [1]: http://freedomdefined.org/Licenses/NC

**Comment by franrua** [comment]
Para obter o link empreguei o selector  proporcionado pola creativecommons.org, que xenera un link de forma automática, pero parece que non o fai correctamente e non me fixara no erro.
Ó final decidin permitir o uso comercial do mesmo, así que agora o problema debería estar correxido.

**Comment by ssaavedra** [comment]
Oh, vaia. 

Bueno, agora iso está xenial!
Respecto ás dúbidas do tema comercial, o enlace que puxen antes xustifica porqué NonCommercial non é de cultura libre, por se queres telo máis claro. E por suposto, ante calquera cousa que quede, tamén estamos aquí.
